### ISSUE TITLE
Allow values past 50

### ISSUE THREAD

**Issue by PeterNerlich** [vollyimnetz/ku#1]
The app currently allows selecting tickets from 1 to 50, but not more. Depending on the liking of the bar team, it might be nice to have higher numbers available and not having to switch to lower numbers mid-bar-session.

As simply adding more buttons would complicate usage on small screens, they could be paginated or placed in a scroll container, compacting the space they take up.

**Comment by vollyimnetz** [comment]
Hi @PeterNerlich,
i really do not think you need more than 50 numbers.
Its a matter of organizing: we used multiple stacks of preprinted paper sheets. On each sheet you have the large number (that the customer gets) a cutline and small number (with some space for the order). Once you reach the number 50 you restart at 1. The customers who had the number 1 before will have had their plate for a long time in the meantime. Just make sure to get the sheet with the large number from the customer so they didnt able to use the number twice.
